version: "3"
services:
  container:
    container_name: js-container
    ports:
      - "3020:3003"
    build:
      context: ./js-container
      dockerfile: Dockerfile
    volumes:
      - "./js-container:/var/app"
      - "/var/app/node_modules"
  nav:
    container_name: js-nav
    ports:
      - "3023:8501"
    build:
      context: ./js-nav
      dockerfile: Dockerfile
    volumes:
      - "./js-nav:/var/app"
      - "/var/app/node_modules"
  product:
    container_name: js-product
    ports:
      - "3021:3002"
    build:
      context: ./js-product
      dockerfile: Dockerfile
    volumes:
      - "./js-product:/var/app"
      - "/var/app/node_modules"
  cart:
    container_name: js-cart
    ports:
      - "3022:4200"
    build:
      context: ./js-cart
      dockerfile: Dockerfile
    volumes:
      - "./js-cart:/var/app"
      - "/var/app/node_modules"
